#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-contest
Version  : 0.1.3
Release  : 2
URL      : https://rubygems.org/downloads/contest-0.1.3.gem
Source0  : https://rubygems.org/downloads/contest-0.1.3.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-test-unit

%description
Contest
=======
Contexts for Test::Unit.
Description
-----------
Write declarative tests using nested contexts without performance penalties. Contest is less than 100 lines of code and gets the job done.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n contest-0.1.3
gem spec %{SOURCE0} -l --ruby > rubygem-contest.gemspec

%build
gem build rubygem-contest.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
contest-0.1.3.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/contest-0.1.3
ruby -v -I.:lib:test test*/*_test.rb
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/contest-0.1.3.gem
/usr/lib64/ruby/gems/2.2.0/doc/contest-0.1.3/ri/Test/Unit/TestCase/cdesc-TestCase.ri
/usr/lib64/ruby/gems/2.2.0/doc/contest-0.1.3/ri/Test/Unit/TestCase/context-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/contest-0.1.3/ri/Test/Unit/TestCase/context_name-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/contest-0.1.3/ri/Test/Unit/TestCase/describe-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/contest-0.1.3/ri/Test/Unit/TestCase/remove_tests-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/contest-0.1.3/ri/Test/Unit/TestCase/sanitize_name-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/contest-0.1.3/ri/Test/Unit/TestCase/setup-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/contest-0.1.3/ri/Test/Unit/TestCase/should-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/contest-0.1.3/ri/Test/Unit/TestCase/teardown-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/contest-0.1.3/ri/Test/Unit/TestCase/test-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/contest-0.1.3/ri/Test/Unit/TestCase/test_name-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/contest-0.1.3/ri/Test/Unit/TestSuite/cdesc-TestSuite.ri
/usr/lib64/ruby/gems/2.2.0/doc/contest-0.1.3/ri/Test/Unit/TestSuite/empty%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/contest-0.1.3/ri/Test/Unit/cdesc-Unit.ri
/usr/lib64/ruby/gems/2.2.0/doc/contest-0.1.3/ri/Test/cdesc-Test.ri
/usr/lib64/ruby/gems/2.2.0/doc/contest-0.1.3/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/contest-0.1.3/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/contest-0.1.3/README.markdown
/usr/lib64/ruby/gems/2.2.0/gems/contest-0.1.3/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/contest-0.1.3/lib/contest.rb
/usr/lib64/ruby/gems/2.2.0/gems/contest-0.1.3/rails/init.rb
/usr/lib64/ruby/gems/2.2.0/gems/contest-0.1.3/test/all_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/contest-0.1.3/test/setup_and_teardown_order_test.rb
/usr/lib64/ruby/gems/2.2.0/specifications/contest-0.1.3.gemspec
